### ISSUE TITLE
Login dialog - excessive invocation of checkCredentials function

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-jmx#31]
On the login dialog, the password field `ng-change` binds to `checkCredentials()`. This means for every character entered, a request is sent to the target Jolokia instance. If a long password is entered, this results in many requests being sent in a potentially very short period of time.

Maybe it's best to just call `checkCredentials` when the login button is clicked.

**Comment by tadayosi** [comment]
I believe @akieling can explain this.

**Comment by abkieling** [comment]
@jamesnetherton @tadayosi @astefanutti 
This is not a bug but it's something that could be improved. If I invoke `checkCredentials()` when the user clicks on the Connect button then the browser blocks the `window.open()` call. The code in the Promise `then` function doesn't seem to be in the same context as the code invoked when the button is clicked. To avoid that, I check the credentials when the user is typing the password. When the user clicks on Connect, I already know if the credentials are correct. The problem is that the Jolokia API returns status 403, which gets logged as an error in the console. We could implement a new endpoint in hawtio-war to check the credentials and use different status codes. What do you think? Any other ideas?

**Comment by jamesnetherton** [comment]
Yes, the warnings output to the console log aren't great. When there have been lots of keystrokes, it almost looks like someone's been trying a brute force password hack! For WildFly / EAP I see 2 log entries per typed character.

I still think we should avoid making network calls on every keystroke if we can.

**Comment by abkieling** [comment]
@jamesnetherton I've made some changes. Please test and let me know what you think.

**Comment by jamesnetherton** [comment]
It works (sort of). But the browser login dialog seems to have made a return:

![hawtio-login](https://user-images.githubusercontent.com/4721408/33771512-24b1f34c-dc29-11e7-9a2e-eb8b968d5c55.png)

**Comment by abkieling** [comment]
Please make sure you have the latest version of @hawtio/node-backend (3.0.4). Besides, when you run an angularjs app (hawtio-jmx, hawtio-integration, ...) without the hawtio server-side stuff, there is no login page, so we have to use the browser popup in those cases.

**Comment by jamesnetherton** [comment]
Ok... retested. Looks much better. Thanks!
